[tool.poetry]
name = "hello-garden"
version = "0.0.1"
description = "Hello Garden"
authors = ["Thomas D. <asteroide@domtombox.net>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/asteroide/hello-garden"
repository = "https://github.com/asteroide/hello-garden"
documentation = "https://hello-garden.readthedocs.io"
classifiers = [
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/asteroide/hello-garden/releases"

[tool.poetry.dependencies]
python = "^3.7.1"
click = "^7.0"
dash = "^1.19.0"
pandas = "^1.2.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
coverage = {extras = ["toml"], version = "^5.4"}
safety = "^1.10.3"
mypy = "^0.800"
typeguard = "^2.10.0"
xdoctest = {extras = ["colors"], version = "^0.15.3"}
sphinx = "^3.4.3"
sphinx-autobuild = "^2020.9.1"
pre-commit = "^2.10.0"
flake8 = "^3.8.4"
black = "^20.8b1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.11.1"
flake8-docstrings = "^1.7.0"
flake8-rst-docstrings = "^0.0.14"
pep8-naming = "^0.11.1"
darglint = "^1.5.8"
reorder-python-imports = "^2.3.6"
pre-commit-hooks = "^3.4.0"
sphinx-rtd-theme = "^0.5.1"
sphinx-click = "^2.5.0"
Pygments = "^2.7.4"
pylint = "^2.7.2"

[tool.poetry.scripts]
hello-garden = "hello_garden.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["hello_garden"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
